### ISSUE TITLE
 Could not resolve project :react-native-gpay

### ISSUE THREAD

**Issue by 57912130** [JadavChirag/react-native-GPay#2]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-gpay.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-gpay: None of the consumable configurations have attributes.

**Comment by ronastlelobo** [comment]
Same Here. @57912130  did you rectify it ??

**Comment by 57912130** [comment]
> 同样在这里。@ 57912130 你纠正了吗？

Didn't solve

**Comment by hellochirag** [comment]
Please follow proper setup configuration step. You can't face this issue.

**Comment by JadavChirag** [comment]
Please follow proper setup configuration step. You can't face this issue.

**Comment by saeedtkh** [comment]
I follow all the steps and I ran into the same error!

```
ould not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-gpay.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-gpay: None of the consumable configurations have attributes.
```

**Comment by hellochirag** [comment]
Okay I'll check it again and update change publish very soon, i'll also update feature of AndroidX.
Thank You

**Comment by ShridharCodewave** [comment]
Same issue. Any solution?

**Comment by rmcclus1** [comment]
I get the same exact error using react-native: 0.58.6

**Comment by EsdrasXavier** [comment]
Same issue here, using react-native: 0.59.5

**Comment by Wilson-Lim** [comment]
AM also facing this issue, any help ?

**Comment by ming-undefined** [comment]
same issue. Any update on this?

**Comment by dlewis2017** [comment]
Same issue. Posted the question again because I didn't check "Closed" issues.
https://github.com/JadavChirag/react-native-GPay/issues/5#issue-489382312
Ran into issues running the demo as well but this would be an awesome tool to utilize was I get it up and running! Any ideas why this is happening? @JadavChirag

**Comment by simonerighi96** [comment]
Same here. Tested on React Native 0.58.6, can we get any update on why this is happening?

**Comment by ramainen** [comment]
I get the same exact error using expo SDK33

**Comment by JollyGolf** [comment]
Same issue. RN 0.61.5

**Comment by okechukwu0127** [comment]
Just landed into this same issue just now. 
RN: 0.58.9

Did the Linking as specified on the Doc.
Also added the Meta tag on my AndroidManifest.

why is this beautifu module not working ?
