### ISSUE TITLE
Add Gpay in IOS

### ISSUE THREAD

**Issue by jinkalr-itpath** [JadavChirag/react-native-GPay#8]
Hello,

Can I use this package for Gpay with **IOS**?
As I have downloaded source from git but there is no **IOS** folder over there.

And please suggest me right package for Gpay with **IOS** in **react native**

Waiting for response.

Thanks.

**Comment by JadavChirag** [comment]
Hello Jinkalr,

this lib for Android Google Pay wallet, iOS not support google wallet, we are working on cross platform google pay with UPI feature and will upgrade repo soon.

I welcome and encourage all pull requests. It usually will take me within 24-48 hours to respond to any issue or request. Here are some basic rules to follow to ensure timely addition of your request:

Match the document style as closely as possible.
Please keep PR titles easy to read and descriptive of changes, this will make them easier to merge :)
Pull requests must be made against master branch for this particular repository.
Check for existing issues first, before filing an issue.
Make sure you follow the set standard as all other projects in this repo do
Have fun!

**Comment by hellochirag** [comment]
Hello Jinkalr,

this lib for Android Google Pay wallet, iOS not support google wallet, we are working on cross platform google pay with UPI feature and will upgrade repo soon.

I welcome and encourage all pull requests. It usually will take me within 24-48 hours to respond to any issue or request. Here are some basic rules to follow to ensure timely addition of your request:

Match the document style as closely as possible.
Please keep PR titles easy to read and descriptive of changes, this will make them easier to merge :)
Pull requests must be made against master branch for this particular repository.
Check for existing issues first, before filing an issue.
Make sure you follow the set standard as all other projects in this repo do
Have fun!
